<?php

/**
 * @file
 * Islandora Defaults stuff.
 */

/**
 * Implements hook_rdf_namespaces().
 */
function islandora_defaults_rdf_namespaces() {
  return [
    'relators' => 'http://id.loc.gov/vocabulary/relators/',
  ];
}

/**
 * Implements hook_theme().
 */
function islandora_defaults_theme() {
  return [
    'file_video_with_caption' => [
      'template' => 'file-video-caption',
      'variables' => [
        'caption' => NULL,
        'files' => [],
        'poster' => NULL,
        'attributes' => NULL,
      ],
    ],
    'file_audio_with_caption' => [
      'template' => 'file-audio-caption',
      'variables' => [
        'caption' => NULL,
        'files' => [],
        'attributes' => NULL,
      ],
    ],
  ];
}
